from crewai import Task
from agent import github_agent, writer_agent

research_task = Task(
    description="""
        Analyze the GitHub profile of {github_username}.

        Extract:
        - Developer overview
        - Main programming languages
        - Technologies and frameworks used
        - Top projects and their purpose
        - Skills demonstrated
        - Contribution activity
        - Notable achievements

        Create a detailed professional summary of the developer.
    """,
    expected_output="""
        A comprehensive summary of the GitHub profile including skills,
        technologies, projects, achievements, and overall developer profile.
    """,
    agent=github_agent
)

blog_writing_task = Task(
    description="""
        Review the GitHub profile summary generated by the GitHub Profile Analyzer.

        Create an engaging blog article that includes:
        - Introduction
        - Developer background
        - Key skills and technologies
        - Highlighted projects
        - Achievements and contributions
        - Conclusion

        Make the blog professional, informative, and easy to read.
    """,
    expected_output="""
        A complete well-structured blog post based on the GitHub profile summary.
    """,
    agent=writer_agent,
    context = [research_task]
)